#!/bin/bash

# Script to help copy .env content for GitHub Secret
# ⚠️ WARNING: This script does NOT display the actual .env content for security reasons

echo "=================================================="
echo "📋 HƯỚNG DẪN CẬP NHẬT GITHUB SECRET"
echo "=================================================="
echo ""
echo "Secret name: BACKEND_ENV_FILE"
echo "Repository: https://github.com/Lwents/SunEdu/settings/secrets/actions"
echo ""
echo "=================================================="
echo ""
echo "⚠️  VÌ LÝ DO BẢO MẬT, SCRIPT NÀY KHÔNG HIỂN THỊ NỘI DUNG .ENV"
echo ""
echo "Để lấy nội dung .env:"
echo "1. Mở file backend/.env trong editor"
echo "2. Copy toàn bộ nội dung"
echo "3. Paste vào GitHub Secret BACKEND_ENV_FILE"
echo ""
echo "Hoặc chạy lệnh:"
echo "  cat backend/.env"
echo ""
echo "=================================================="
echo ""
echo "Các bước cập nhật GitHub Secret:"
echo "1. Vào: https://github.com/Lwents/SunEdu/settings/secrets/actions"
echo "2. Tìm secret 'BACKEND_ENV_FILE'"
echo "3. Click 'Update'"
echo "4. Paste nội dung .env"
echo "5. Click 'Update secret'"
echo ""
echo "⚠️  LƯU Ý: Đảm bảo file .env có đầy đủ:"
echo "   - ALLOWED_HOSTS=127.0.0.1,localhost,api.smartedu.click"
echo "   - CSRF_TRUSTED_ORIGINS=...https://api.smartedu.click..."
echo "   - CORS_ALLOWED_ORIGINS=...https://api.smartedu.click..."
echo ""

