# Generated by Django 5.2.5 on 2025-11-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_passwordchangeotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordchangeotp',
            new_name='custom_acco_user_id_62d7f2_idx',
            old_name='custom_acc_user_id_6af29d_idx',
        ),
    ]
