# Generated by Django 5.2.5 on 2025-11-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_lessonquestionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonquestionreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonquestionreaction',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='activities.lessonquestion'),
        ),
        migrations.AlterField(
            model_name='exercisesettings',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesettings',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonquestionreaction',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='activities.lessonquestionreply'),
        ),
        migrations.AddConstraint(
            model_name='lessonquestionreaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('reply__isnull', True)), models.Q(('question__isnull', True), ('reply__isnull', False)), _connector='OR'), name='lesson_question_reaction_must_have_question_or_reply'),
        ),
    ]
