# Generated by Django 5.2.5 on 2025-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_exercisesettings_show_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='grade',
            field=models.CharField(blank=True, help_text="Lớp của bài kiểm tra (ví dụ: '1', '2', '3', '4', '5'). Nếu có lesson, sẽ lấy từ course.grade", max_length=16, null=True),
        ),
    ]
