# Generated by Django 5.2.5 on 2025-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_merge_course_and_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessonquestionreport',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('question__isnull', False), ('reply__isnull', True)),
                    models.Q(('question__isnull', True), ('reply__isnull', False)),
                    _connector='OR',
                ),
                name='lesson_question_report_must_have_question_or_reply',
            ),
        ),
    ]
