# Generated by Django 5.2.5 on 2025-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introduction',
            field=models.TextField(blank=True, help_text='Giới thiệu chi tiết về khóa học (hiển thị ở trang chi tiết)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Giá khóa học (0 = miễn phí)', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Ảnh bìa khóa học', null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL video giới thiệu (ví dụ: YouTube link)', null=True),
        ),
    ]
