# Generated by Django 5.2.5 on 2025-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_introduction_course_price_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='File video khóa học (nếu không dùng URL)', null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL video khóa học (ví dụ: YouTube link hoặc link video trực tiếp)', null=True),
        ),
    ]
