# Generated by Django 5.2.5 on 2025-11-14 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_enrollment_course_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='introduction',
            field=models.TextField(blank=True, help_text='Giới thiệu bài học (hiển thị trước video)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_exercise_completion',
            field=models.BooleanField(default=False, help_text='Yêu cầu hoàn thành bài tập trước khi tiếp tục'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='File video cho bài học', null=True, upload_to='lesson_videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL video cho bài học', null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('quiz', 'Quiz'), ('exploration_ref', 'Exploration Reference'), ('introduction', 'Introduction'), ('exercise_ref', 'Exercise Reference')], max_length=32),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video_watched', models.BooleanField(default=False)),
                ('exercise_completed', models.BooleanField(default=False)),
                ('exercise_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
