# Generated by Django 5.2.5 on 2025-11-16 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_lesson_introduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('math', 'Toán'), ('vietnamese', 'Tiếng Việt'), ('english', 'Tiếng Anh'), ('science', 'Khoa học'), ('history', 'Lịch sử')], default='math', max_length=32)),
                ('type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('doc', 'Tài liệu'), ('quiz', 'Quiz')], default='video', max_length=32)),
                ('grade_band', models.CharField(choices=[('Khối 1–2', 'Khối 1–2'), ('Khối 3–5', 'Khối 3–5')], default='Khối 1–2', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Library Item',
                'verbose_name_plural': 'Content Library Items',
                'ordering': ['-updated_at'],
            },
        ),
    ]
