# Generated by Django 5.2.5 on 2025-12-11 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRestoration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restored_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('month_year', models.CharField(db_index=True, help_text='Format: YYYY-MM (e.g., 2025-12)', max_length=7)),
                ('restored_streak_value', models.IntegerField(default=0, help_text='Giá trị streak đã được khôi phục')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_restorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak Restoration',
                'verbose_name_plural': 'Streak Restorations',
                'ordering': ['-restored_at'],
                'indexes': [models.Index(fields=['user', 'month_year'], name='ai_personal_user_id_e66c60_idx'), models.Index(fields=['user', '-restored_at'], name='ai_personal_user_id_8f2236_idx')],
            },
        ),
    ]
